# Venture Funding with Deep Learning

## Instructions

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

**Instructions:**

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

**Prepare the Data for Use on a Neural Network Model**

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

**Compile and Evaluate a Binary Classification Model Using a Neural Network**

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

**Optimize the Neural Network Model**

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

## <font color=LimeGreen>\~\~\~begin code\~\~\~</font>

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

# custom functions
from custom_functions.compose_neural_network import (
    encode_categorical_variables,
    create_features_and_target,
    scale_features_data,
    binary_class_neural_net
)

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(Path('./Resources/applicants_data.csv'))

# Review the DataFrame
applicant_data_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN','NAME'])  

# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### <font color=OrangeRed>**COMBINED STEPS 3 & 4**</font>

In [5]:
# Encode categorical variables and combine with numerical variables
# into a new DataFrame
encoded_df = encode_categorical_variables(applicant_data_df)

# Review the encoded DataFrame
encoded_df

Categorical Variables:
['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']

Combined Encoded DataFrame:
       STATUS   ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_T10  \
0           1      5000              1                   1.0
1           1    108590              1                   0.0
2           1      5000              0                   0.0
3           1      6692              1                   0.0
4           1    142590              1                   0.0
...       ...       ...            ...                   ...
34294       1      5000              0                   0.0
34295       1      5000              0                   0.0
34296       1      5000              0                   0.0
34297       1      5000              1                   0.0
34298       1  36500179              0                   0.0

       APPLICATION_TYPE_T12  APPLICATION_TYPE_T13  APPLICATION_TYPE_T14  \
0                       0.0                   0.0                   0.0
1                       0.0                   0.0                   0.0
2                       0.0                   0.0                   0.0
3                       0.0                   0.0                   0.0
4                       0.0                   0.0                   0.0
...                     ...                   ...                   ...
34294                   0.0                   0.0                   0.0
34295                   0.0                   0.0                   0.0
34296                   0.0                   0.0                   0.0
34297                   0.0                   0.0                   0.0
34298                   0.0                   0.0                   0.0

       APPLICATION_TYPE_T15  APPLICATION_TYPE_T17  APPLICATION_TYPE_T19  ...  \
0                       0.0                   0.0                   0.0  ...
1                       0.0                   0.0                   0.0  ...
2                       0.0                   0.0                   0.0  ...
3                       0.0                   0.0                   0.0  ...
4                       0.0                   0.0                   0.0  ...
...                     ...                   ...                   ...  ...
34294                   0.0                   0.0                   0.0  ...
34295                   0.0                   0.0                   0.0  ...
34296                   0.0                   0.0                   0.0  ...
34297                   0.0                   0.0                   0.0  ...
34298                   0.0                   0.0                   0.0  ...

       INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0                    0.0                     0.0                       0.0
1                    1.0                     0.0                       0.0
2                    0.0                     0.0                       0.0
3                    0.0                     1.0                       0.0
4                    0.0                     0.0                       1.0
...                  ...                     ...                       ...
34294                0.0                     0.0                       0.0
34295                0.0                     0.0                       0.0
34296                0.0                     0.0                       0.0
34297                0.0                     0.0                       0.0
34298                0.0                     0.0                       0.0

       INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0                     0.0               0.0                     0.0
1                     0.0               0.0                     0.0
2                     0.0               0.0                     0.0
3                     0.0               0.0                     0.0
4                     0.0               0.0                     0.0
...                   ...               ...                     ...
34294                 0.0               0.0                     0.0
34295                 0.0               0.0                     0.0
34296                 0.0               0.0                     0.0
34297                 0.0               0.0                     0.0
34298                 0.0               1.0                     0.0

       INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  \
0                  0.0                0.0                       1.0
1                  0.0                0.0                       1.0
2                  0.0                0.0                       1.0
3                  0.0                0.0                       1.0
4                  0.0                0.0                       1.0
...                ...                ...                       ...
34294              0.0                0.0                       1.0
34295              0.0                0.0                       1.0
34296              0.0                0.0                       1.0
34297              0.0                0.0                       1.0
34298              0.0                0.0                       1.0

       SPECIAL_CONSIDERATIONS_Y
0                           0.0
1                           0.0
2                           0.0
3                           0.0
4                           0.0
...                         ...
34294                       0.0
34295                       0.0
34296                       0.0
34297                       0.0
34298                       0.0

[34299 rows x 117 columns]

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### <font color=OrangeRed>*collapsed steps 3 & 4*</font>

#### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [6]:
# Create a list of categorical variables 
# categorical_variables = # YOUR CODE HERE

# Display the categorical variables list
# YOUR CODE HERE

In [7]:
# Create a OneHotEncoder instance
# enc = # YOUR CODE HERE

In [8]:
# Encode the categorcal variables using OneHotEncoder
# encoded_data = # YOUR CODE HERE

In [9]:
# Create a DataFrame with the encoded variables
# encoded_df = # YOUR CODE HERE

# Review the DataFrame
# YOUR CODE HERE

#### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [10]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
# encoded_df = # YOUR CODE HERE

# Review the Dataframe
# YOUR CODE HERE

### <font color=OrangeRed>**COMBINED STEP 5**</font>

In [11]:
# This custom function assigns the target ~then~ the features 
target, features  = create_features_and_target(encoded_df,"IS_SUCCESSFUL",True)

Target Dataset (y):
0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

Features Dataset:
       STATUS   ASK_AMT  APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  \
0           1      5000                   1.0                   0.0
1           1    108590                   0.0                   0.0
2           1      5000                   0.0                   0.0
3           1      6692                   0.0                   0.0
4           1    142590                   0.0                   0.0
...       ...       ...                   ...                   ...
34294       1      5000                   0.0                   0.0
34295       1      5000                   0.0                   0.0
34296       1      5000                   0.0                   0.0
34297       1      5000                   0.0                   0.0
34298       1  36500179                   0.0                   0.0

       APPLICATION_TYPE_T13  APPLICATION_TYPE_T14  APPLICATION_TYPE_T15  \
0                       0.0                   0.0                   0.0
1                       0.0                   0.0                   0.0
2                       0.0                   0.0                   0.0
3                       0.0                   0.0                   0.0
4                       0.0                   0.0                   0.0
...                     ...                   ...                   ...
34294                   0.0                   0.0                   0.0
34295                   0.0                   0.0                   0.0
34296                   0.0                   0.0                   0.0
34297                   0.0                   0.0                   0.0
34298                   0.0                   0.0                   0.0

       APPLICATION_TYPE_T17  APPLICATION_TYPE_T19  APPLICATION_TYPE_T2  ...  \
0                       0.0                   0.0                  0.0  ...
1                       0.0                   0.0                  0.0  ...
2                       0.0                   0.0                  0.0  ...
3                       0.0                   0.0                  0.0  ...
4                       0.0                   0.0                  0.0  ...
...                     ...                   ...                  ...  ...
34294                   0.0                   0.0                  0.0  ...
34295                   0.0                   0.0                  0.0  ...
34296                   0.0                   0.0                  0.0  ...
34297                   0.0                   0.0                  0.0  ...
34298                   0.0                   0.0                  0.0  ...

       INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0                    0.0                     0.0                       0.0
1                    1.0                     0.0                       0.0
2                    0.0                     0.0                       0.0
3                    0.0                     1.0                       0.0
4                    0.0                     0.0                       1.0
...                  ...                     ...                       ...
34294                0.0                     0.0                       0.0
34295                0.0                     0.0                       0.0
34296                0.0                     0.0                       0.0
34297                0.0                     0.0                       0.0
34298                0.0                     0.0                       0.0

       INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0                     0.0               0.0                     0.0
1                     0.0               0.0                     0.0
2                     0.0               0.0                     0.0
3                     0.0               0.0                     0.0
4                     0.0               0.0                     0.0
...                   ...               ...                     ...
34294                 0.0               0.0                     0.0
34295                 0.0               0.0                     0.0
34296                 0.0               0.0                     0.0
34297                 0.0               0.0                     0.0
34298                 0.0               1.0                     0.0

       INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  \
0                  0.0                0.0                       1.0
1                  0.0                0.0                       1.0
2                  0.0                0.0                       1.0
3                  0.0                0.0                       1.0
4                  0.0                0.0                       1.0
...                ...                ...                       ...
34294              0.0                0.0                       1.0
34295              0.0                0.0                       1.0
34296              0.0                0.0                       1.0
34297              0.0                0.0                       1.0
34298              0.0                0.0                       1.0

       SPECIAL_CONSIDERATIONS_Y
0                           0.0
1                           0.0
2                           0.0
3                           0.0
4                           0.0
...                         ...
34294                       0.0
34295                       0.0
34296                       0.0
34297                       0.0
34298                       0.0

[34299 rows x 116 columns]

### <font color=OrangeRed>*collapsed step 5*</font>

#### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [12]:
# Define the target set y using the IS_SUCCESSFUL column
# y = # YOUR CODE HERE

# Display a sample of y
# YOUR CODE HERE

In [13]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
# X = # YOUR CODE HERE

# Review the features DataFrame
# YOUR CODE HERE

### Step 6: Split the features and target sets into training and testing datasets.

In [14]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(
    features,
    target,
    random_state=1
)

### <font color=OrangeRed>**COMBINED STEP 7**</font>

In [15]:
# Scale the features data
X_train_scaled, X_test_scaled = scale_features_data(X_train, X_test)

### <font color=OrangeRed>*collapsed step 7*</font>

#### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [16]:
# Create a StandardScaler instance
# scaler = # YOUR CODE HERE

# Fit the scaler to the features training dataset
# X_scaler = # YOUR CODE HERE

# Fit the scaler to the features training dataset
# X_train_scaled = # YOUR CODE HERE
# X_test_scaled = # YOUR CODE HERE

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### <font color=OrangeRed>**COMBINED STEP 1**</font>

In [17]:
# Define inputs for the function
# to build and compile the model
number_input_features = len(X_train.iloc[0])
hidden_node_layers = []     # List of lists to hold hidden node layer info

# The first sub-item assigns the number of hidden nodes in the layer
# The second sub-item assigns the activation function for the layer

# Hidden node layer 1
hidden_node_layers.append(
        [
                (number_input_features + 1) // 2,
                'relu'
        ]
)

# Hidden node layer 2
hidden_node_layers.append(
        [
                (hidden_node_layers[0][0] + 1) // 2,
                'relu'
        ]
)

# Activation function for the output layer
output_layer_activation = 'sigmoid'

# NOTE: This function currently supports ONLY ONE output neuron
nn = binary_class_neural_net(
        number_input_features,
        hidden_node_layers,
        output_layer_activation
)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 58)                6786
_________________________________________________________________
dense_1 (Dense)              (None, 29)                1711
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 30
=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(
    X_train_scaled,
    y_train,
    epochs=50
)

Epoch 1/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5785 - accuracy: 0.7206
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7292
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5522 - accuracy: 0.7307
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5501 - accuracy: 0.7306
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7319
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7333
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7330
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7331
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7344
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7338
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7341
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7355
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7358
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7364
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5400 - accuracy: 0.7356
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7367
Epoch 17/50
804/804 [==============================] - 1s 974us/step - loss: 0.5394 - accuracy: 0.7368
Epoch 18/50
804/804 [==============================] - 1s 933us/step - loss: 0.5394 - accuracy: 0.7364
Epoch 19/50
804/804 [==============================] - 1s 935us/step - loss: 0.5393 - accuracy: 0.7365
Epoch 20/50
804/804 [==============================] - 1s 939us/step - loss: 0.5384 - accuracy: 0.7372
Epoch 21/50
804/804 [==============================] - 1s 942us/step - loss: 0.5378 - accuracy: 0.7378
Epoch 22/50
804/804 [==============================] - 1s 938us/step - loss: 0.5379 - accuracy: 0.7368
Epoch 23/50
804/804 [==============================] - 1s 968us/step - loss: 0.5368 - accuracy: 0.7385
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7386
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5371 - accuracy: 0.7381
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5365 - accuracy: 0.7379
Epoch 27/50
804/804 [==============================] - 1s 983us/step - loss: 0.5367 - accuracy: 0.7379
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7376
Epoch 29/50
804/804 [==============================] - 1s 933us/step - loss: 0.5363 - accuracy: 0.7383
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7389
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5354 - accuracy: 0.7389
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5348 - accuracy: 0.7388
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7392
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5342 - accuracy: 0.7394
Epoch 35/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5348 - accuracy: 0.7393
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7408
Epoch 37/50
804/804 [==============================] - 1s 958us/step - loss: 0.5338 - accuracy: 0.7409
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5338 - accuracy: 0.7398
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7401
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7400
Epoch 41/50
804/804 [==============================] - 1s 995us/step - loss: 0.5332 - accuracy: 0.7406
Epoch 42/50
804/804 [==============================] - 1s 956us/step - loss: 0.5328 - accuracy: 0.7408
Epoch 43/50
804/804 [==============================] - 1s 936us/step - loss: 0.5329 - accuracy: 0.7407
Epoch 44/50
804/804 [==============================] - 1s 943us/step - loss: 0.5328 - accuracy: 0.7413
Epoch 45/50
804/804 [==============================] - 1s 988us/step - loss: 0.5327 - accuracy: 0.7413
Epoch 46/50
804/804 [==============================] - 1s 938us/step - loss: 0.5324 - accuracy: 0.7416
Epoch 47/50
804/804 [==============================] - 1s 974us/step - loss: 0.5327 - accuracy: 0.7409
Epoch 48/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5322 - accuracy: 0.7415
Epoch 49/50
804/804 [==============================] - 1s 956us/step - loss: 0.5324 - accuracy: 0.7406
Epoch 50/50
804/804 [==============================] - 1s 985us/step - loss: 0.5319 - accuracy: 0.7400

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [19]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(
    X_test_scaled,
    y_test,
    verbose=2
)

# Display the model loss and accuracy results
print(f'\nModel Results:\n    Loss: {model_loss:%}\n    Accuracy: {model_accuracy:%}')

268/268 - 0s - loss: 0.5545 - accuracy: 0.7306

Model Results:
    Loss: 55.445474%
    Accuracy: 73.061222%

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [31]:
# Set the model's file path
file_path = Path('./Resources/AlphabetSoup.h5')

# Export your model to a HDF5 file
if not file_path.is_file():
    nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

<font color=LimeGreen>**Rewind:**</font> Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:

- [ ] Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
- [x] Add more neurons (nodes) to a hidden layer. -- <font color=Crimson>**Alternative Model 3**</font>
- [x] Add more hidden layers. -- <font color=Crimson>**Alternative Model 1**</font>
- [ ] Use different activation functions for the hidden layers.
- [x] Add to or reduce the number of epochs in the training regimen. -- <font color=Crimson>**Alternative Model 2**</font>

### Alternative Model 1

In [21]:
# Define the inputs for the model

# Implemented shorthand for alternative models:
# 'nif_am1' = number_input_features_alt_model_1
# 'hnl_am1' = hidden_node_layers_alt_model_1
# 'ola_am1' = output_layer_activation_alt_model_1

nif_am1 = len(X_train.iloc[0])

hnl_am1 = []     # List of lists to hold hidden node layer info

# The first sub-item assigns the number of hidden nodes in the layer
# The second sub-item assigns the activation function for the layer

# Hidden node layer 1
hnl_am1.append(
        [
                (nif_am1 + 1) // 2,
                'relu'
        ]
)

# Hidden node layer 2
hnl_am1.append(
        [
                (hnl_am1[0][0] + 1) // 2,
                'relu'
        ]
)

# Hidden node layer 3
hnl_am1.append(
        [
                (hnl_am1[1][0] + 1) // 2,
                'relu'
        ]
)

# Activation function for the output layer
ola_am1 = 'sigmoid'

# NOTE: This function currently supports ONLY ONE output neuron
nn_am1 = binary_class_neural_net(
        nif_am1,
        hnl_am1,
        ola_am1
)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 58)                6786
_________________________________________________________________
dense_4 (Dense)              (None, 29)                1711
_________________________________________________________________
dense_5 (Dense)              (None, 15)                450
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 16
=================================================================
Total params: 8,963
Trainable params: 8,963
Non-trainable params: 0
_________________________________________________________________

In [22]:
# Fit the model with the training data

# 'fm_am1' = fit_model_alt_model_1
fm_am1 = nn_am1.fit(
    X_train_scaled,
    y_train,
    epochs=50
)

Epoch 1/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5723 - accuracy: 0.7220
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5520 - accuracy: 0.7295
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5486 - accuracy: 0.7317
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5463 - accuracy: 0.7318
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5452 - accuracy: 0.7322
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7343
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5436 - accuracy: 0.7339
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7354
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7362
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7366
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7366
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7373
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5398 - accuracy: 0.7367
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7375
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7372
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7384
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7375
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7385
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7381
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7387
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7392
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7392
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7397
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7387
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7397
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7387
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7392
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5354 - accuracy: 0.7388
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7399
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7404
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7394
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5342 - accuracy: 0.7404
Epoch 33/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5339 - accuracy: 0.7406
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7391
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7404
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7402
Epoch 37/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7404
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7406
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7417
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7394
Epoch 41/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7410
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7411
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7409
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7415
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5322 - accuracy: 0.7414
Epoch 46/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5322 - accuracy: 0.7417
Epoch 47/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7416
Epoch 48/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7420
Epoch 49/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7421
Epoch 50/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5315 - accuracy: 0.7413

### Alternative Model 2

In [23]:
# Define the inputs for the model

# Implemented shorthand for alternative models:
# 'nif_am2' = number_input_features_alt_model_2
# 'hnl_am2' = hidden_node_layers_alt_model_2
# 'ola_am2' = output_layer_activation_alt_model_2

nif_am2 = len(X_train.iloc[0])

hnl_am2 = []     # List of lists to hold hidden node layer info

# The first sub-item assigns the number of hidden nodes in the layer
# The second sub-item assigns the activation function for the layer

# Hidden node layer 1
hnl_am2.append(
        [
                (nif_am2 + 1) // 2,
                'relu'
        ]
)

# Hidden node layer 2
hnl_am2.append(
        [
                (hnl_am2[0][0] + 1) // 2,
                'relu'
        ]
)

# Activation function for the output layer
ola_am2 = 'sigmoid'

# NOTE: This function currently supports ONLY ONE output neuron
nn_am2 = binary_class_neural_net(
        nif_am2,
        hnl_am2,
        ola_am2
)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_7 (Dense)              (None, 58)                6786
_________________________________________________________________
dense_8 (Dense)              (None, 29)                1711
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 30
=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

In [24]:
# Fit the model with the training data

# 'fm_am2' = fit_model_alt_model_2
fm_am2 = nn_am2.fit(
    X_train_scaled,
    y_train,
    epochs=100
)

Epoch 1/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5728 - accuracy: 0.7217
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5531 - accuracy: 0.7278
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5503 - accuracy: 0.7313
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7318
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5463 - accuracy: 0.7339
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5454 - accuracy: 0.7353
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7348
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7352
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7354
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7355
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7364
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7360
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7367
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7372
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7362
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7366
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7376
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7374
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7392
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5380 - accuracy: 0.7378
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7383
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7388
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7386
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7379
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5364 - accuracy: 0.7383
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5364 - accuracy: 0.7382
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5364 - accuracy: 0.7390
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5360 - accuracy: 0.7389
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7390
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5356 - accuracy: 0.7388
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7399
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5351 - accuracy: 0.7398
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5349 - accuracy: 0.7398
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5348 - accuracy: 0.7397
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7401
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7392
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7394
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7410
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7394
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5339 - accuracy: 0.7403
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7407
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7403
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7401
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7407
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7399
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7398
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7407
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5325 - accuracy: 0.7402
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7424
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7401
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7402
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7414
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7412
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7408
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7407
Epoch 56/100
804/804 [==============================] - 1s 967us/step - loss: 0.5314 - accuracy: 0.7418
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7409
Epoch 58/100
804/804 [==============================] - 1s 983us/step - loss: 0.5314 - accuracy: 0.7404
Epoch 59/100
804/804 [==============================] - 1s 954us/step - loss: 0.5313 - accuracy: 0.7416
Epoch 60/100
804/804 [==============================] - 1s 959us/step - loss: 0.5312 - accuracy: 0.7408
Epoch 61/100
804/804 [==============================] - 1s 950us/step - loss: 0.5312 - accuracy: 0.7418
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5311 - accuracy: 0.7414
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5306 - accuracy: 0.7416
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5311 - accuracy: 0.7418
Epoch 65/100
804/804 [==============================] - 1s 947us/step - loss: 0.5304 - accuracy: 0.7406
Epoch 66/100
804/804 [==============================] - 1s 941us/step - loss: 0.5308 - accuracy: 0.7426
Epoch 67/100
804/804 [==============================] - 1s 948us/step - loss: 0.5305 - accuracy: 0.7413
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5304 - accuracy: 0.7419
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5299 - accuracy: 0.7417
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5299 - accuracy: 0.7414
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5296 - accuracy: 0.7419
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5302 - accuracy: 0.7420
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5302 - accuracy: 0.7423
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5302 - accuracy: 0.7417
Epoch 75/100
804/804 [==============================] - 1s 976us/step - loss: 0.5296 - accuracy: 0.7421
Epoch 76/100
804/804 [==============================] - 1s 950us/step - loss: 0.5300 - accuracy: 0.7415
Epoch 77/100
804/804 [==============================] - 1s 950us/step - loss: 0.5296 - accuracy: 0.7417
Epoch 78/100
804/804 [==============================] - 1s 956us/step - loss: 0.5301 - accuracy: 0.7413
Epoch 79/100
804/804 [==============================] - 1s 953us/step - loss: 0.5292 - accuracy: 0.7413
Epoch 80/100
804/804 [==============================] - 1s 952us/step - loss: 0.5294 - accuracy: 0.7423
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5294 - accuracy: 0.7423
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5292 - accuracy: 0.7424
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7417
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5291 - accuracy: 0.7422
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7420
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5290 - accuracy: 0.7419
Epoch 87/100
804/804 [==============================] - 1s 956us/step - loss: 0.5291 - accuracy: 0.7428
Epoch 88/100
804/804 [==============================] - 1s 957us/step - loss: 0.5287 - accuracy: 0.7427
Epoch 89/100
804/804 [==============================] - 1s 970us/step - loss: 0.5289 - accuracy: 0.7412
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5287 - accuracy: 0.7429
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5291 - accuracy: 0.7419
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5288 - accuracy: 0.7423
Epoch 93/100
804/804 [==============================] - 1s 968us/step - loss: 0.5282 - accuracy: 0.7434
Epoch 94/100
804/804 [==============================] - 1s 977us/step - loss: 0.5289 - accuracy: 0.7427
Epoch 95/100
804/804 [==============================] - 1s 969us/step - loss: 0.5280 - accuracy: 0.7422
Epoch 96/100
804/804 [==============================] - 1s 977us/step - loss: 0.5288 - accuracy: 0.7428
Epoch 97/100
804/804 [==============================] - 1s 989us/step - loss: 0.5282 - accuracy: 0.7430
Epoch 98/100
804/804 [==============================] - 1s 981us/step - loss: 0.5288 - accuracy: 0.7420
Epoch 99/100
804/804 [==============================] - 1s 981us/step - loss: 0.5283 - accuracy: 0.7428
Epoch 100/100
804/804 [==============================] - 1s 991us/step - loss: 0.5282 - accuracy: 0.7426

Alternative Model 3

In [25]:
# Define the inputs for the model

# Implemented shorthand for alternative models:
# 'nif_am3' = number_input_features_alt_model_3
# 'hnl_am3' = hidden_node_layers_alt_model_3
# 'ola_am3' = output_layer_activation_alt_model_3

nif_am3 = len(X_train.iloc[0])

hnl_am3 = []     # List of lists to hold hidden node layer info

# The first sub-item assigns the number of hidden nodes in the layer
# The second sub-item assigns the activation function for the layer

# Hidden node layer 1
hnl_am3.append(
        [
                nif_am3 // 2,
                'relu'
        ]
)

# Hidden node layer 2
hnl_am3.append(
        [
                (hnl_am3[0][0] + 1) // 2,
                'relu'
        ]
)

# Activation function for the output layer
ola_am3 = 'sigmoid'

# NOTE: This function currently supports ONLY ONE output neuron
nn_am3 = binary_class_neural_net(
        nif_am3,
        hnl_am3,
        ola_am3
)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_10 (Dense)             (None, 58)                6786
_________________________________________________________________
dense_11 (Dense)             (None, 29)                1711
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 30
=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [26]:
print(f'Original Model Results:\n')

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(
    X_test_scaled,
    y_test,
    verbose=2
)

# Display the model loss and accuracy results
print(f'\nLoss: {model_loss}, Accuracy: {model_accuracy}')

Original Model Results:

268/268 - 0s - loss: 0.5545 - accuracy: 0.7306

Loss: 0.5544547438621521, Accuracy: 0.7306122183799744

In [27]:
print(f'Alternative Model 1 Results:\n')

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_am1.evaluate(
    X_test_scaled,
    y_test,
    verbose=2
)

# Display the model loss and accuracy results
print(f'\nLoss: {model_loss}, Accuracy: {model_accuracy}')

Alternative Model 1 Results:

268/268 - 0s - loss: 0.5557 - accuracy: 0.7313

Loss: 0.5557029247283936, Accuracy: 0.7313119769096375

In [28]:
print(f'Alternative Model 2 Results:\n')

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_am2.evaluate(
    X_test_scaled,
    y_test,
    verbose=2
)

# Display the model loss and accuracy results
print(f'\nLoss: {model_loss}, Accuracy: {model_accuracy}')

Alternative Model 2 Results:

268/268 - 0s - loss: 0.5624 - accuracy: 0.7293

Loss: 0.5624309778213501, Accuracy: 0.7293294668197632

In [29]:
print(f'Alternative Model 3 Results:\n')

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_am3.evaluate(
    X_test_scaled,
    y_test,
    verbose=2
)

# Display the model loss and accuracy results
print(f'\nLoss: {model_loss}, Accuracy: {model_accuracy}')

Alternative Model 3 Results:

268/268 - 0s - loss: 0.7245 - accuracy: 0.4679

Loss: 0.7244995832443237, Accuracy: 0.4678717255592346

<font color=Crimson>**Outcome of Alternative Model 1:**</font>

- For this first alternative model, an additional hidden node layer was added with a number of hidden nodes derived utilizing the same methodology used to go from `hidden_node_layer1` to `hidden_node_layer2` in the original model which included adding `1` to the number of hidden nodes from the previous hidden layer (`hidden_node_layer1` to `hidden_node_layer2`) then dividing that output by `2` using *floor division*.

- The results of the first alternative model did not make any noticeable improvement over the original model and only managed to reduce the model's **loss** by <font color=cyan>~0.2%</font>, but also reduce the model's **accuracy** by <font color=cyan>~0.1%</font>.

- Overall, in the case of this particular dataset, the additional hidden node layer using the same node number methodology does <font color=Red><u>**not**</u></font> provide any worthwhile improvement.

### Step 3: Save each of your alternative models as an HDF5 file.

In [30]:
# Set the file path for the first alternative model
file_path = # YOUR CODE HERE

# Export your model to a HDF5 file
# YOUR CODE HERE

SyntaxError: invalid syntax (<ipython-input-30-24965d0a0162>, line 2)

In [ ]:
# Set the file path for the second alternative model
file_path = # YOUR CODE HERE

# Export your model to a HDF5 file
# YOUR CODE HERE